services:
  api:
    build:
      context: ./compras           # carpeta donde están src/ y el Dockerfile bueno
      dockerfile: Dockerfile
    container_name: compras
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg://user:password@db:5432/comprasdb
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: postgres:16-alpine
    container_name: compras_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: comprasdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata: