services:
  db:
    image: postgres:16-alpine
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./bff/app/db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
  
  bff:
    build:
      context: ./bff          # Dockerfile y wsgi.py aquí
      dockerfile: Dockerfile
    container_name: bff
    ports:
      - "8001:8000"                  # distinto de api
    env_file:
      - ./bff/.env             # variables SOLO de este micro
    volumes:
      - ~/.aws:/root/.aws:ro         # credenciales AWS del host
    command: >
      gunicorn -b 0.0.0.0:8000 wsgi:app
    restart: unless-stopped

volumes:
  pgdata: