services:
  localstack:
    image: localstack/localstack:3
    environment:
      - SERVICES=sqs
      - AWS_DEFAULT_REGION=us-east-1
    ports: ["4566:4566"]
    healthcheck:
      test: ["CMD","bash","-c","awslocal sqs list-queues || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 30

  init-sqs:
    image: localstack/localstack:3
    environment:
      - LOCALSTACK_HOST=localstack
      - AWS_DEFAULT_REGION=us-east-1
    depends_on:
      localstack:
        condition: service_healthy
    volumes:
      - ./app/consumer/scripts/init-sqs.sh:/init-sqs.sh:ro
    entrypoint: [ "bash", "-lc", "/init-sqs.sh" ]


  haproxy:
    image: haproxy:2.9
    volumes:
      - ./app/load-balancer/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    command: ["haproxy","-W","-db","-f","/usr/local/etc/haproxy/haproxy.cfg"]
    ports: ["8080:8080","8404:8404"]

  consumer:
    image: python:3.12-slim
    working_dir: /app
    command: bash -lc "pip install --no-cache-dir boto3 httpx && python worker.py"
    volumes:
      - ./app/consumer/worker.py:/app/worker.py:ro  # ✅ Ruta correcta
    environment:
      - AWS_REGION=us-east-1
      - SQS_ENDPOINT=http://localstack:4566
      - SQS_QUEUE_URL=http://localstack:4566/000000000000/orders.fifo
      - LB_TARGET_URL=http://haproxy:8080/orders
      - SQS_BATCH=10
      - SQS_WAIT=20
      - SQS_VISIBILITY=60
      - HTTP_TIMEOUT=30
      # Credenciales dummy para LocalStack:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    depends_on:
      localstack:
        condition: service_healthy
      init-sqs:
        condition: service_completed_successfully
